# Guition ESP32-P4-JC8012P4A1 Immich Frame
substitutions:
  name: "immich-frame-10inch"
  friendly_name: "Immich Frame 10inch"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  espframe:
    url: https://github.com/rverdam/espframe
    files: [devices/guition-esp32-p4-jc8012p4a1/packages.yaml]
    ref: main
    refresh: 1s